{{- if eq .Values.appConfig.backupDriver "s3" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.appConfig.s3.secretName }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
{{- end}}